FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY pom.xml .
COPY src ./src
COPY system.properties .

RUN ./mvnw package -DskipTests

CMD ["java", "-jar", "target/game-24points-0.0.1-SNAPSHOT.jar"]